# Generated by Django 3.2 on 2023-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000000000, null=True)),
                ('job_description', models.CharField(max_length=1000000000, null=True)),
                ('job_city', models.CharField(max_length=1000000000, null=True)),
                ('job_city_postal', models.CharField(max_length=1000000000, null=True)),
                ('company_name', models.CharField(max_length=1000000000, null=True)),
                ('email_to_apply', models.CharField(max_length=1000000000, null=True)),
                ('user_posted', models.CharField(max_length=1000000000, null=True)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=1000000000, null=True)),
            ],
        ),
    ]
