# Generated by Django 3.2 on 2023-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=1000000000, null=True)),
                ('product_description', models.CharField(max_length=1000000000, null=True)),
                ('brand', models.CharField(max_length=1000000000, null=True)),
                ('stock', models.CharField(max_length=1000000000, null=True)),
                ('user_posted', models.CharField(max_length=1000000000, null=True)),
                ('product_types', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing/Fashion', 'Clothing and Fashion'), ('Stationery', 'Stationery'), ('Beverages', 'Beverages'), ('Pets', 'Pets'), ('Jewelry', 'Jewelry'), ('Home-Furniture', 'Home-Furniture'), ('Beauty', 'Beauty'), ('Books/Media', 'Books/Media'), ('Toys/Games', 'Toys/Games'), ('Health/Wellness', 'Health/Wellness'), ('Automotive', 'Automotive'), ('Home-Improvement', 'Home-Improvement'), ('Sports/Outdoors', 'Sports/Outdoors')], max_length=1000000000, null=True)),
            ],
        ),
    ]
