# Generated by Django 3.2 on 2023-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_productdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdata',
            name='user_id',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='user_id',
            field=models.CharField(max_length=10000000000, null=True),
        ),
    ]
