# Generated by Django 3.2 on 2023-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20230903_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='price',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
