# Generated by Django 3.2 on 2023-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_rename_product_types_productdata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='contact_number',
            field=models.CharField(max_length=10000000000, null=True),
        ),
    ]
