# Generated by Django 4.2.5 on 2023-09-26 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
