# Generated by Django 4.2.5 on 2023-09-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_contact_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sno',
            new_name='Serial',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='datetime',
            new_name='Time',
        ),
    ]
