# Generated by Django 4.2.5 on 2023-09-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_rename_mail_contact_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='subject',
        ),
    ]
