# Generated by Django 4.2.5 on 2023-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_rename_mail_contact_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
